apiVersion: v1
kind: Service
metadata:
  name: kyoto-postgresql-nodeport
  labels:
    app: kyoto-postgresql-nodeport
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: kyoto-postgresql