apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyoto-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyoto-postgresql
  template:
    metadata:
      labels:
        app: kyoto-postgresql
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/kyoto-postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim          